# Project information
site_name: 'Résumé'
site_description: 'information page'
site_author: 'wzdbsss'

# Copyright
copyright: 'Copyright &copy; 2019'

# Documentation and theme
theme:
  name: 'alabaster'
