# Project information
site_name: 'Résumé'

site_author: 'wzdbsss'

# Copyright
copyright: 'Copyright &copy; 2019'

# Documentation and theme
theme:
  name: 'alabaster'
  custom_dir: 'alabaster/'

markdown_extensions:
  - toc:
      permalink: "¶"
