# Project information
site_name: 'Résumé'
site_description: 'information page'
site_author: 'wzdbsss'

# Copyright
copyright: 'Copyright &copy; 2019'

# Documentation and theme
theme:
  name: 'alabaster'

markdown_extensions:
  - toc:
      permalink: "¶"

extra:
  show_powered_by: false
  homepage_nav: false
  include_toc: yes